'''

These items are only for the addendum data

'''

unpublished = set([ 
    'Lung_IPF_1', 'Lung_IPF_2', 'Lung_IPF_3', 'Lung_IPF_4', 'Lung_IPF_5', 'Lung_IPF_6', 'Lung_IPF_7', 'Lung_IPF_8',
    'invitro_DA_neurons_sporadicPD_1', 'invitro_DA_neurons_sporadicPD_2', 
    'invitro_DA_neurons_twin_nonPD_1', 'invitro_DA_neurons_twin_nonPD_2', 'invitro_DA_neurons_twin_nonPD_3', 'invitro_DA_neurons_twin_nonPD_4',
    'invitro_DA_neurons_twin_PD_1', 'invitro_DA_neurons_twin_PD_2', 'invitro_DA_neurons_twin_PD_3', 'invitro_DA_neurons_twin_PD_4',  
    'cortical_neuron_park2a_cccp_20h',
    'cortical_neuron_park2a_cccp_8h',
    'cortical_neuron_park2a_ctrl_0h',
    'cortical_neuron_park2a_h2o2_3h',
    'cortical_neuron_park2a_h2o2_6h',
    'cortical_neuron_park2a_mg132_20h',
    'cortical_neuron_park2a_mg132_8h',
    'cortical_neuron_park2b_cccp_20h',
    'cortical_neuron_park2b_cccp_8h',
    'cortical_neuron_park2b_ctrl_0h',
    'cortical_neuron_park2b_h2o2_3h',
    'cortical_neuron_park2b_h2o2_6h',
    'cortical_neuron_park2b_mg132_20h',
    'cortical_neuron_park2b_mg132_8h',
    'cortical_neuron_park7a_cccp_20h',
    'cortical_neuron_park7a_cccp_8h',
    'cortical_neuron_park7a_ctrl_0h',
    'cortical_neuron_park7a_h2o2_3h',
    'cortical_neuron_park7a_h2o2_6h',
    'cortical_neuron_park7a_mg132_20h',
    'cortical_neuron_park7a_mg132_8h',
    'cortical_neuron_park7b_cccp_20h',
    'cortical_neuron_park7b_cccp_8h',
    'cortical_neuron_park7b_ctrl_0h',
    'cortical_neuron_park7b_h2o2_3h',
    'cortical_neuron_park7b_h2o2_6h',
    'cortical_neuron_park7b_mg132_20h',
    'cortical_neuron_park7b_mg132_8h',
    'cortical_neuron_pink1a_cccp_20h',
    'cortical_neuron_pink1a_cccp_8h',
    'cortical_neuron_pink1a_ctrl_0h',
    'cortical_neuron_pink1a_h2o2_3h',
    'cortical_neuron_pink1a_h2o2_6h',
    'cortical_neuron_pink1a_mg132_20h',
    'cortical_neuron_pink1a_mg132_8h',
    'cortical_neuron_pink1b_cccp_20h',
    'cortical_neuron_pink1b_cccp_8h',
    'cortical_neuron_pink1b_ctrl_0h',
    'cortical_neuron_pink1b_h2o2_3h',
    'cortical_neuron_pink1b_h2o2_6h',
    'cortical_neuron_pink1b_mg132_20h',
    'cortical_neuron_pink1b_mg132_8h',
    'cortical_neuron_wta_cccp_20h',
    'cortical_neuron_wta_cccp_8h',
    'cortical_neuron_wta_h2o2_3h',
    'cortical_neuron_wta_h2o2_6h',
    'cortical_neuron_wta_mg132_20h',
    'cortical_neuron_wta_mg132_8h',
    'cortical_neuron_wtb_cccp_20h',
    'cortical_neuron_wtb_cccp_8h',
    'cortical_neuron_wtb_h2o2_3h',
    'cortical_neuron_wtb_h2o2_6h',
    'cortical_neuron_wtb_mg132_20h',
    'cortical_neuron_wtb_mg132_8h',
    'cortical_neuron_wtc_cccp_20h',
    'cortical_neuron_wtc_cccp_8h',
    'cortical_neuron_wtc_h2o2_3h',
    'cortical_neuron_wtc_h2o2_6h',
    'cortical_neuron_wtc_mg132_20h',
    'cortical_neuron_wtc_mg132_8h',
    'hESC_liver_diff_d0_hESC_1',
    'hESC_liver_diff_d11_hepatoblast_1',
    'hESC_liver_diff_d13_hepatocyte_1',
    'hESC_liver_diff_d1_DE_1',
    'hESC_liver_diff_d21_hepatocyte_1',
    'hESC_liver_diff_d2_DE_1',
    'hESC_liver_diff_d3_DE_1',
    'hESC_liver_diff_d5_hepatoblast_1',
    'hESC_liver_diff_d7_hepatoblast_1',
    'hESC_liver_diff_d9_hepatoblast_1',
    ])